services:
  java:
    build: 
      context: .
      target: java
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - maven_cache:/root/.m2
    entrypoint: /bin/bash
    command: -c "sleep infinity"

  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ./terraform:/workspace
      - ~/.aws:/root/.aws
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    working_dir: /workspace
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - TF_VAR_tf_state_bucket
      - TF_VAR_tf_state_key_infra
      - TF_VAR_image_tag

  tflint:
    image: ghcr.io/terraform-linters/tflint:latest
    volumes:
      - .:/data

volumes:
  maven_cache: null
