name: Build Pipeline

on: [  push , pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest-arm

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run Tests
      run: make test

  build:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest-arm
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build      
      run: IMAGE_REGISTRY=ghcr.io IMAGE_NAME=${{ github.repository }} IMAGE_TAG=${{ github.sha }} make build-native

    - name: Push
      if: github.ref == 'refs/heads/main'
      run: IMAGE_REGISTRY=ghcr.io IMAGE_NAME=${{ github.repository }} IMAGE_TAG=${{ github.sha }} make release