name: Deploy

on:
  workflow_dispatch:
    inputs:               
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - 'c3lifesandbox01use1'
      type:
        description: 'Terraform Run Type'
        required: true
        type: choice
        options:
          - 'plan'
          - 'apply'
          - 'destroy'
jobs:
  deploy:
    runs-on: ubuntu-latest-arm

    permissions:
      id-token: write 
      contents: read   

    environment: ${{ github.event.inputs.environment }} 

    env:
      AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_WORKSPACE: ${{ github.event.inputs.environment }}
      TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/github-${{ github.event.repository.name }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Fetching GitHub App token to access private repositories
        uses: actions/create-github-app-token@v1
        id: tf-modules-auth
        with:
          app-id: ${{ secrets.TF_MODULES_APP_ID }}
          private-key: ${{ secrets.TF_MODULES_PK }}
          owner: ${{ github.repository_owner }}

      - name: Configure git client to use GitHub App token
        run:  git config --global url."https://x-access-token-:${{ steps.tf-modules-auth.outputs.token }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: Terraform Init
        run: make init

      - name: Terraform Run
        run: make ${{ github.event.inputs.type }}